# Generated by Django 5.0 on 2026-08-27 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlatformCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='e.g. CertMaster, LinkedIn Learning', max_length=100)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_credentials', to='admissions.student')),
            ],
            options={
                'verbose_name': 'Learning Platform Credential',
                'verbose_name_plural': 'Learning Platform Credentials',
                'db_table': 'learning_platform_credentials',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the reviewer', null=True)),
                ('current_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_requests', to='academics.enrollment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_promotions', to='academics.class')),
            ],
            options={
                'verbose_name': 'Promotion Request',
                'verbose_name_plural': 'Promotion Requests',
                'db_table': 'promotions',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Withdrawn', 'Withdrawn')], default='In Progress', max_length=20)),
                ('assignment_type', models.CharField(choices=[('Default', 'Default'), ('Elective', 'Elective')], default='Default', help_text='Default = auto-assigned on registration, Elective = manually added', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_modules', to='academics.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_modules', to='admissions.student')),
            ],
            options={
                'verbose_name': 'Student Module',
                'verbose_name_plural': 'Student Modules',
                'db_table': 'student_modules',
                'ordering': ['student', 'module'],
                'unique_together': {('student', 'module')},
            },
        ),
        migrations.CreateModel(
            name='LocalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(help_text='Numeric mark achieved e.g. 75')),
                ('competent', models.BooleanField(help_text='True = Competent, False = Not Yet Competent')),
                ('assessment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments_recorded', to=settings.AUTH_USER_MODEL)),
                ('student_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_assessments', to='assessments.studentmodule')),
            ],
            options={
                'verbose_name': 'Local Assessment',
                'verbose_name_plural': 'Local Assessments',
                'db_table': 'local_assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('eBook', 'eBook'), ('Exam Voucher', 'Exam Voucher'), ('Platform', 'Platform Access'), ('Other', 'Other')], max_length=20)),
                ('key_value', models.CharField(help_text='The actual key or access code', max_length=500)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('student_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_keys', to='assessments.studentmodule')),
            ],
            options={
                'verbose_name': 'Access Key',
                'verbose_name_plural': 'Access Keys',
                'db_table': 'access_keys',
            },
        ),
        migrations.CreateModel(
            name='InternationalExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(help_text='Sequential attempt number e.g. 1 for first attempt, 2 for resit')),
                ('exam_date', models.DateField()),
                ('exam_result', models.BooleanField(help_text='True = Passed, False = Failed')),
                ('score', models.IntegerField(blank=True, help_text='Numeric score if provided by the certifying body', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_attempts', to='assessments.studentmodule')),
            ],
            options={
                'verbose_name': 'International Exam Attempt',
                'verbose_name_plural': 'International Exam Attempts',
                'db_table': 'int_exam_attempts',
                'ordering': ['student_module', 'attempt_number'],
                'unique_together': {('student_module', 'attempt_number')},
            },
        ),
    ]
