# Generated by Django 6.1 on 2026-08-28 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localassessment',
            options={'ordering': ['student_module', 'assessment_type'], 'verbose_name': 'Local Assessment', 'verbose_name_plural': 'Local Assessments'},
        ),
        migrations.AddField(
            model_name='localassessment',
            name='assessment_type',
            field=models.CharField(choices=[('PFA01', 'Formative 1'), ('PFA02', 'Formative 2'), ('PSA', 'Summative')], default='PFA01', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='localassessment',
            unique_together={('student_module', 'assessment_type')},
        ),
        migrations.AddField(
            model_name='localassessment',
            name='is_remediation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localassessment',
            name='remediation_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='localassessment',
            name='assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localassessment',
            name='competent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localassessment',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localassessment',
            name='student_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_assessments', to='assessments.studentmodule'),
        ),
        migrations.AlterField(
            model_name='localassessment',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='localassessment',
            name='created_at',
        ),
    ]
