# Generated by Django 6.1 on 2026-09-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_internationalexamattempt_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='assessments.internationalexamattempt')),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_bookings_made', to=settings.AUTH_USER_MODEL)),
                ('student_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_bookings', to='assessments.studentmodule')),
            ],
            options={
                'verbose_name': 'Exam Booking',
                'verbose_name_plural': 'Exam Bookings',
                'db_table': 'exam_bookings',
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
    ]
