# Generated by Django 6.1 on 2026-09-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_exambooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
