# Generated by Django 6.1 on 2026-09-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_applicant_is_historical_onboarding'),
        ('assessments', '0005_delete_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Credentials', 'Access Credentials'), ('Labs', 'Labs')], max_length=20)),
                ('vendor_name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform Table',
                'verbose_name_plural': 'Platform Tables',
                'db_table': 'platform_tables',
                'ordering': ['section', 'order', 'id'],
                'unique_together': {('section', 'vendor_name')},
            },
        ),
        migrations.CreateModel(
            name='PlatformRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_rows', to='admissions.student')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='assessments.platformtable')),
            ],
            options={
                'verbose_name': 'Platform Row',
                'verbose_name_plural': 'Platform Rows',
                'db_table': 'platform_rows',
                'ordering': ['id'],
                'unique_together': {('table', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PlatformColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('column_type', models.CharField(choices=[('Text', 'Text'), ('Password', 'Password')], default='Text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='assessments.platformtable')),
            ],
            options={
                'verbose_name': 'Platform Column',
                'verbose_name_plural': 'Platform Columns',
                'db_table': 'platform_columns',
                'ordering': ['table', 'order', 'id'],
                'unique_together': {('table', 'label')},
            },
        ),
        migrations.CreateModel(
            name='PlatformRowValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assessments.platformcolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assessments.platformrow')),
            ],
            options={
                'verbose_name': 'Platform Row Value',
                'verbose_name_plural': 'Platform Row Values',
                'db_table': 'platform_row_values',
                'unique_together': {('row', 'column')},
            },
        ),
    ]
