# Generated by Django 6.1 on 2026-09-08 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_seed_platform_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalexamattempt',
            name='pass_threshold',
            field=models.IntegerField(default=700, help_text='Minimum score (out of 1000) required to pass this exam.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='internationalexamattempt',
            name='score',
            field=models.IntegerField(help_text='Score out of 1000. Required.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
