# Generated by Django 6.1 on 2026-09-08 19:43
#
# NQF5 simplification (client instruction): LocalAssessment collapses from
# 3 rows per StudentModule (PFA01/PFA02/PSA, with marks/remediation) to a
# single Competent/Not Yet Competent rating + comment per StudentModule.
# The old 3-per-module rows are cleared first (all empty at the time of
# writing — verified via `SELECT COUNT(*) ... WHERE mark IS NOT NULL` /
# `WHERE competent IS NOT NULL`, both 0 — so nothing of value is lost)
# since they'd otherwise violate the new OneToOneField's unique constraint
# on student_module_id before it's even added.

import django.db.models.deletion
from django.db import migrations, models


def clear_local_assessments(apps, schema_editor):
    LocalAssessment = apps.get_model('assessments', 'LocalAssessment')
    LocalAssessment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_internationalexamattempt_pass_threshold_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_local_assessments, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='localassessment',
            options={'ordering': ['student_module'], 'verbose_name': 'NQF5 Assessment', 'verbose_name_plural': 'NQF5 Assessments'},
        ),
        migrations.AlterUniqueTogether(
            name='localassessment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='localassessment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localassessment',
            name='competency',
            field=models.CharField(blank=True, choices=[('Competent', 'Competent'), ('Not Yet Competent', 'Not Yet Competent')], help_text='Left blank until the trainer grades this module.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='localassessment',
            name='student_module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_assessment', to='assessments.studentmodule'),
        ),
        migrations.RemoveField(
            model_name='localassessment',
            name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='localassessment',
            name='competent',
        ),
        migrations.RemoveField(
            model_name='localassessment',
            name='is_remediation',
        ),
        migrations.RemoveField(
            model_name='localassessment',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='localassessment',
            name='remediation_mark',
        ),
    ]
