# Generated by Django 5.0 on 2026-08-27 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('id_type', models.CharField(choices=[('SA ID', 'South African ID'), ('Passport', 'Passport'), ('Asylum', 'Asylum Document')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('residential_status', models.CharField(choices=[('Citizen', 'Citizen'), ('Permanent Resident', 'Permanent Resident'), ('Asylum Seeker', 'Asylum Seeker'), ('Foreign National', 'Foreign National')], max_length=30)),
                ('personal_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('residential_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=200)),
                ('last_school_year', models.IntegerField(help_text='Last year the applicant attended school e.g. 2022')),
                ('disability_status', models.CharField(blank=True, help_text='Describe any disability or leave blank for none', max_length=200, null=True)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Waitlisted', 'Waitlisted')], default='Pending', max_length=20)),
                ('status_date', models.DateField(blank=True, help_text='Date the status was last changed', null=True)),
                ('popi_consent', models.BooleanField(default=False, help_text='Records whether the applicant consented to data processing under POPIA. Optional.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='academics.campus')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='academics.program')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'db_table': 'applicant_details',
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(blank=True, help_text='School-issued email address for platform access', max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to='admissions.applicant')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student_details',
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.DateField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumni', to='academics.campus')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumni', to='academics.program')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alumni_record', to='admissions.student')),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
                'db_table': 'alumni',
                'ordering': ['-graduation_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=50)),
                ('cell', models.CharField(max_length=20)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='admissions.applicant')),
            ],
            options={
                'verbose_name': 'Student Contact',
                'verbose_name_plural': 'Student Contacts',
                'db_table': 'student_contact',
            },
        ),
    ]
