# Generated by Django 6.1 on 2026-08-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_applicant_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='application_reference',
            field=models.CharField(blank=True, help_text='Auto-generated application reference number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('Word of Mouth', 'Word of Mouth'), ('Facebook', 'Facebook'), ('Exhibition', 'Exhibition'), ('Find a Friend', 'Find a Friend'), ('Website', 'Website')], help_text='How did the applicant hear about ITCA?', max_length=20, null=True),
        ),
    ]
