# Generated by Django 6.1 on 2026-08-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_applicant_application_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id_code',
            field=models.CharField(blank=True, help_text='Auto-generated student identifier', max_length=30, null=True, unique=True),
        ),
    ]
