# Generated by Django 6.1 on 2026-09-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_student_student_id_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_historical_onboarding',
            field=models.BooleanField(default=False, help_text='True for an existing student being backfilled into the system, rather than a new applicant awaiting an admission decision'),
        ),
    ]
