# Generated by Django 6.1 on 2026-09-08 21:38
#
# Replaces the old referral source options (Word of Mouth, Facebook,
# Exhibition, Find a Friend, Website) with the client's requested list
# (Website, Word Of Mouth, Career Expo, School Outreach, Social Media) —
# this field existed on the model and in PersonalDetailsForm's Meta.fields
# already, but was never actually rendered in step_1_personal.html, so it
# sat empty on every application until now.

from django.db import migrations, models


def normalize_word_of_mouth_casing(apps, schema_editor):
    """
    The only value ever recorded under the old choice set was the exact
    string 'Word of Mouth' (lowercase 'of') — normalize it to the new
    choice's casing ('Word Of Mouth') so existing rows still match a
    valid choice exactly, not just display the same text by coincidence.
    """
    Applicant = apps.get_model('admissions', 'Applicant')
    Applicant.objects.filter(referral_source='Word of Mouth').update(referral_source='Word Of Mouth')


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_applicant_is_historical_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('Website', 'Website'), ('Word Of Mouth', 'Word Of Mouth'), ('Career Expo', 'Career Expo'), ('School Outreach', 'School Outreach'), ('Social Media', 'Social Media')], help_text='How did the applicant hear about ITCA?', max_length=20, null=True),
        ),
        migrations.RunPython(normalize_word_of_mouth_casing, migrations.RunPython.noop),
    ]
