# Generated by Django 6.1 on 2026-09-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_applicant_referral_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='application_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
