# Generated by Django 5.0 on 2026-08-27 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('entra_id', models.CharField(blank=True, help_text='Microsoft Entra ID object ID — set automatically on first login', max_length=255, null=True, unique=True)),
                ('email', models.EmailField(help_text="Must match the user's Microsoft/Outlook email address", max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('exec_admin', 'Executive Admin'), ('test_admin', 'Test Admin'), ('trainer', 'Trainer'), ('data_capturer', 'Data Capturer')], default='data_capturer', help_text='Controls what this user can see and do in the portal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('campus', models.ForeignKey(blank=True, help_text='Leave blank for Exec Admins who oversee all campuses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='academics.campus')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'db_table': 'system_users',
            },
        ),
    ]
