# Generated by Django 5.0 on 2026-08-27 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(help_text='Full name of the campus e.g. Durban, Pietermaritzburg', max_length=100, unique=True)),
                ('campus_code', models.CharField(help_text='Short code used in reports e.g. DBN, PMB', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive campuses are hidden from dropdowns but data is retained')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'db_table': 'campuses',
                'ordering': ['campus_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn'), ('Promoted', 'Promoted')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('module_code', models.CharField(max_length=50, unique=True)),
                ('is_local_assessment', models.BooleanField(default=False, help_text='Has a local NQF5 assessment graded by the trainer')),
                ('is_international_assessment', models.BooleanField(default=False, help_text='Has an international certification exam e.g. CompTIA, Microsoft')),
                ('certifying_body', models.CharField(blank=True, help_text='e.g. CompTIA, Microsoft — only required if is_international_assessment is True', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
                'ordering': ['module_name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100, unique=True)),
                ('program_code', models.CharField(help_text='Short code displayed on the dashboard e.g. CYB, SFTW', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive programs are hidden from new enrollments but data is retained')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
                'ordering': ['program_name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Auto-assign this module to new students in this program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Program Module',
                'verbose_name_plural': 'Program Modules',
                'db_table': 'program_modules',
                'ordering': ['program', 'module'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(help_text='The year this class runs e.g. 2024')),
                ('cohort', models.CharField(choices=[('New', 'New'), ('Returning', 'Returning')], default='New', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.campus')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'ordering': ['-academic_year', 'program', 'campus'],
            },
        ),
    ]
