# Generated by Django 5.0 on 2026-08-27 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='trainer',
            field=models.ForeignKey(blank=True, help_text='The trainer responsible for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_group',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.class'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='admissions.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_modules', to='academics.module'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_modules', to='academics.program'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('program', 'campus', 'academic_year', 'cohort')},
        ),
        migrations.AlterUniqueTogether(
            name='programmodule',
            unique_together={('program', 'module')},
        ),
    ]
