# Generated by Django 6.1 on 2026-08-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(default=30, help_text='Maximum number of students allowed in this class'),
        ),
    ]
