# Generated by Django 6.1 on 2026-09-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.DateField(help_text='e.g. 1 February — informational; nothing is automated off this date yet.')),
                ('year_end', models.DateField(help_text='e.g. 15 December — New-cohort students are automatically promoted to Returning on this date.')),
                ('last_promoted_year', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Calendar',
                'verbose_name_plural': 'Academic Calendar',
                'db_table': 'academic_calendar',
            },
        ),
    ]
